# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='text',
            new_name='imageText',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
