# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import image_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to=image_server.models.image_path),
        ),
    ]
