# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_images')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
